### ISSUE TITLE
重建效果不太理想

### ISSUE THREAD

**Issue by guyingy** [EAST-J/Youtubehand#1]
麻烦问一下，我输入了一张图片发现重建效果不太好，想问问您有什么解决途径吗

**Comment by EAST-J** [comment]
可以提供一下具体的图片例子吗

**Comment by guyingy** [comment]
我输入自己的数据，输出的关节位置的识别也有些误差，重建的结果也不是很好&nbsp;


Gy
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月12日(星期天) 中午11:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [EAST-J/Youtubehand] 重建效果不太理想 (Issue #1)





 
可以提供一下具体的图片例子吗

**Comment by guyingy** [comment]
我也用freihand数据集中的图片尝试了一下，重建效果也不太好




请问是我在运行文件时的操作有问题吗？您有好的解决办法吗？




Gy
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "EAST-J/Youtubehand"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月12日(星期天) 中午11:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [EAST-J/Youtubehand] 重建效果不太理想 (Issue #1)





 
可以提供一下具体的图片例子吗

**Comment by EAST-J** [comment]
由于之前复现的权重找不到了，我周末重新训练下，可以再实验下效果

**Comment by guyingy** [comment]
好的&nbsp; 感谢感谢！如果有结果了请您告诉我一下
&nbsp;


Gy
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月16日(星期四) 下午2:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [EAST-J/Youtubehand] 重建效果不太理想 (Issue #1)





 
由于之前复现的权重找不到了，我周末重新训练下，可以再实验下效果

**Comment by EAST-J** [comment]
> 好的&nbsp; 感谢感谢！如果有结果了请您告诉我一下 &nbsp; Gy ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年3月16日(星期四) 下午2:15 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [EAST-J/Youtubehand] 重建效果不太理想 (Issue #1) 由于之前复现的权重找不到了，我周末重新训练下，可以再实验下效果 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

您好，我同步了下代码并且更新了resnet18的训练结果，你可以下载测试一下

**Comment by guyingy** [comment]
感谢您的更新！用了您的训练结果得到的模型比之前好多了，但是指端处有些瑕疵，请问您有什么好的解决办法吗？
![1](https://user-images.githubusercontent.com/118977024/226110473-497459c2-e2bc-4249-88c9-e76fe6de9016.png)
![2](https://user-images.githubusercontent.com/118977024/226110526-f554952d-15d5-45b2-afce-f327bb241013.png)

**Comment by EAST-J** [comment]
可以尝试改变normal loss和edge loss的超参数权重
