### ISSUE TITLE
将三维模型手映射到二维平面上

### ISSUE THREAD

**Issue by guyingy** [EAST-J/Youtubehand#2]
不好意思再次打扰您！我想要问一下network中输出的pred_camera指的什么呢？我想要将生成的手网格映射到输入的二维图像上，像handmesh中的一样，但是我跑出来的结果偏差较大，我在想是不是因为相机参数的问题，所以想问一下您有什么好的建议吗？感谢
![图片](https://user-images.githubusercontent.com/118977024/228771577-93183e83-b6ee-41db-a626-ebd0dc06ac81.png)
![图片](https://user-images.githubusercontent.com/118977024/228774126-8b1860e6-c572-49db-83ba-bdcb96a00ecd.png)

**Comment by EAST-J** [comment]
Handmesh所使用的应该是GT 相机内参，这里预测的是弱透视投影方法，具体可以参考：https://blog.csdn.net/qq_37099774/article/details/124399583#comments_21824132。
