### ISSUE TITLE
File structure

### ISSUE THREAD

**Issue by Apeng-Rzp** [EAST-J/Youtubehand#3]
Could you please list the folder structure, especially regarding the use of Mano

**Comment by EAST-J** [comment]
You should first make a dir named template, and move MANO_RIGHT.pkl, template.ply, transform.pkl into it.

**Comment by Apeng-Rzp** [comment]
Thank you for your reply. If I want to replace resnet18 with resnet50, do the following commands need to be changed?
`python main.py --split train --batch_size 64 --epochs 38 --decay_step 30 --backbone resnet50 --out_channels 64 128 256 512`
An error message is displayed when I run the `python main.py --split demo --resume $path to trained model$`,

Traceback (most recent call last):
  File "main.py", line 67, in <module>
    main()
  File "main.py", line 42, in main
    model.load_state_dict(checkpoint)
  File "/home/renzhipeng/.conda/envs/youtubehand-main/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1605, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Network:
        Unexpected key(s) in state_dict: "backbone.layer1.2.conv1.weight", "backbone.layer1.2.bn1.weight"........ 

`$path to trained model$`is replaced with `resnet50-checkpoint-38-77330/state_dict`,Is it the reason for setting out_channels? And how do we determine epochs=38?

**Comment by EAST-J** [comment]
1. If you want to train the model with resnet50, I recommend using the commands as:
`python main.py --split train --batch_size 64 --epochs 38 --decay_step 30 --backbone resnet50 --out_channels 256 512 1024 2048`  .
2. The demo commands should also be changed to backbone resnet50 and other settings `python main.py --split demo --resume $path to trained model$ --backbone resnet50`.
3. The epochs are set according to handmesh paper, which is the codebase of my code, you can change the epochs and other hyper-parameters.

**Comment by Apeng-Rzp** [comment]
After your recommendation, I read`Camera-Space Hand Mesh Recovery via Semantic Aggregation and Adaptive 2D-1D Registration`. How do you design your encoder and decoder?

In addition, the following results were obtained by evaluating freihand locally

**Comment by Apeng-Rzp** [comment]
After your recommendation, I read Camera-Space Hand Mesh Recovery via Semantic Aggregation and Adaptive 2D-1D Registration. How do you design your encoder and decoder?

In addition, the following results were obtained by evaluating freihand locally
`xyz_mean3d: 217.759575
xyz_auc3d: 0.000000
xyz_al_mean3d: 0.798449
xyz_al_auc3d: 0.841464
mesh_mean3d: 217.756331
mesh_auc3d: 0.000000
mesh_al_mean3d: 0.804143
mesh_al_auc3d: 0.840033
f_score_5: 0.000000
f_al_score_5: 0.650010
f_score_15: 0.000000
f_al_score_15: 0.969127
`How did you get the PA-MPJPE and PA-MPVPE that you displayed in the project space?
Look forward to your reply and have a nice day！

**Comment by EAST-J** [comment]
1. The encoder and decoder designs are re-produced from this [paper](https://arxiv.org/abs/2004.01946).
2. The xyz_al_mean3d and mesh_al_mean3d mean the PA results
